name: 'csv-flag-keeper'
description: 'Keep your summary sheet'
author: 'seed-of-apricot <seed.of.apricot@dev.chronolapselibrary.net>'
inputs:
  token:
    required: true
    description: 'github token'
  summaryPath:
    required: true
    description: 'the path to the summary file'
  id:
    required: false
    description: 'column name for the id'
    default: 'id'
runs:
  using: 'node12'
  main: 'dist/index.js'
