name: 'csv-flag-keeper'
description: 'Keep your summary sheet'
author: 'seed-of-apricot <seed.of.apricot@dev.chronolapselibrary.net>'
branding:
  icon: align-left
  color: orange
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'github token'
  summaryPath:
    required: true
    description: 'path to the summary file'
  flagPath:
    required: true
    description: 'path to the flag files'
  id:
    required: false
    description: 'column name for the id'
    default: 'id'
runs:
  using: 'node12'
  main: 'dist/index.js'
