name: 'build-test'
on:
  push:
    branches:
      - update-summary
    paths:
      - 'example/flags/**/*.csv'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          summaryPath: 'example/example.csv'
      - uses: peter-evans/create-pull-request@master
        with:
          commit-message: update summary
          title: Update Summary
          body: summary updated
          branch: main
