name: 'build-test'
on:
  push:
    branches:
      - update-summary

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: update-summary
      - name: update-summary
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          summaryPath: example/example.csv
          flagPath: example/flags/*.csv
      - name: pull-request
        uses: peter-evans/create-pull-request@master
        with:
          commit-message: update summary
          title: Update Summary
          body: summary updated
          base: main
